enum CaptchaProviderType {
  ALTCHA
  CAP
  DUMMY
}

enum ConnectionProtocol {
  TCP_TLS
  HTTPS
  UDP
  SSH
  TCP
}

enum InstanceState {
  CREATING
  RUNNING
}

enum UserRole {
  PLAYER
  AUTHOR
  ADMIN
}

type CaptchaChallenge {
  providerType: CaptchaProviderType!
  challenge: String!
}

type CtfCategory {
  id: String!
  name: String!
  description: String
  color: String
}

type CtfChallengeConnectionInfo {
  host: String!
  port: Int!
  protocol: ConnectionProtocol!
  sshUsername: String
  sshPassword: String
}

type CtfChallengeMetadata {
  id: String!
  name: String!
  authors: [String!]!
  descriptionMd: String!
  categories: [String!]!
  difficulty: String!
  attachments: [String!]!
  releaseTime: Int
  endTime: Int
  points: Int!
  canStart: Boolean!
  instance: InstanceStatus
  solved: Boolean!

  # Whether the challenge source code can be exported by the user
  canExport: Boolean!
  solves: Int!
}

type CtfDifficulty {
  id: String!
  name: String!
  color: String
}

type EventConfig {
  eventName: String!
  frontPageMd: String!
  rulesMd: String!
  startTime: Int!
  endTime: Int!
  useTeams: Boolean!
  registrationStartTime: Int
  registrationEndTime: Int
  maxTeamSize: Int
  scoreboardFreezeTime: Int
  categories: [CtfCategory!]!
  difficulties: [CtfDifficulty!]!
}

type InstanceStatus {
  state: InstanceState!
  connectionInfo: [CtfChallengeConnectionInfo!]!
}

type InvalidSubmission {
  challengeId: String!
  submittedFlag: String!
  submittedAt: String!
  user: User!
  challenge: CtfChallengeMetadata!
}

type Mutation {
  login(username: String!, password: String!): SessionCredentials!
  createUser(
    username: String!
    email: String!
    password: String!
    captchaChallenge: String
    captchaResponse: String
  ): Boolean!
  refreshSession(refreshToken: String!): SessionCredentials!
  endSession(refreshToken: String!): Boolean!
  syncRepo: Boolean!
  launchChallengeInstance(challengeId: String!): Boolean!
  stopChallengeInstance(challengeId: String!): Boolean!

  # Returns the ID of the solved challenge if the flag is correct, or null otherwise.
  submitFlag(challengeId: String!, flag: String!): String
  joinTeamWithCode(joinCodeInput: String!): Team!
  createTeam(name: String!, slug: String!, createJoinCode: Boolean!): Team!
  leaveTeam: Boolean!
  enableJoinCode: String!
  disableJoinCode: Boolean!
}

type Query {
  isAuthenticated: Boolean!
  syncStatus: SyncStatus!
  eventConfig: EventConfig!
  challenges: [CtfChallengeMetadata!]!
  users: [User!]!
  me: User
  userById(userId: String!): User
  solves: [Solve!]!
  teams: [Team!]!
  captcha: CaptchaChallenge!
}

type SessionCredentials {
  refreshToken: String!
  accessToken: String!
}

type Solve {
  challengeId: String!
  submittedFlag: String!
  solvedAt: String!
  user: User!
  challenge: CtfChallengeMetadata!
}

type SyncStatus {
  commitHash: String
  commitTimestamp: Int
  commitAuthor: String
  commitTitle: String
  isSynced: Boolean!
}

type Team {
  id: String!
  name: String!
  slug: String!
  joinCode: String
  members: [User!]!
}

type User {
  id: String!
  username: String!
  email: String!
  role: UserRole!
  invalidSubmissionsCount: Int!
  solvesCount: Int!
  invalidSubmissions: [InvalidSubmission!]!
  solves: [Solve!]!
  actor: String!
}
